#!/usr/bin/python3

from database import Session, Media, Root, Encounter
from parse import download
from argparse import ArgumentParser as ap
from datetime import datetime
import locale

def print_example(example):
	if args.verbose:
		print("    {:35.35s} | {:35.35s}".format(
			example.expression or "",
			example.translation or ""))

def print_root(root):
	print()
	for usage in root.usages:
		phon=usage.phonetic or " "
		gram=usage.grammar or "?"
		print("[{:15.15s} {:10.10s} {:s}]".format(usage.address,phon,gram))
		for meaning in usage.meanings:
			for example in meaning.examples:
				print_example(example)	
	for enc in root.encounters:
		print(" ** {:s}".format(enc.media.name))

if __name__ == "__main__":
	parser=ap()
	parser.add_argument("words", nargs="*", help="Words to lookup")		
	parser.add_argument("--verbose","-v", action="store_true",help="Show examples")		
	args=parser.parse_args()

	s = Session()
	now=datetime.now()

	for word in args.words:
		roots=s.query(Root).filter(Root.root.like("%{}%".format(word))).all()
		for root in roots:
			print_root(root)
